### ISSUE TITLE
3rd party organizations on landing page

### ISSUE THREAD

**Issue by danopolan** [danopolan/istqb_latex#78]
Some ISTQB products are developed in cooperation with 3rd parties, which are then mentioned on a landing page. 
Examples can be seen in https://istqb-main-web-prod.s3.amazonaws.com/media/documents/ISTQB_CT-AI_Syllabus_v1.0_mghocmT.pdf or https://istqb-main-web-prod.s3.amazonaws.com/media/documents/ISTQB-CT-UT_Syllabus_v1.0_2018.pdf (ignore copyright Notice on the landing page)

The current landing page layout is challenging with the space. But most of the syllabi has shorter name than ATLaS, and there is usually only one 3rd party to be mentioned. Also, we can tweak the layout a bit in case of a 3rd party.

Acceptance criteria:

- Landing page can be adjusted to mention 3rd party with text: "_Provided by <name of the 3rd party_"
- 3rd party logo can be added
- Multiple 3rd parties can be added
- The change could require TeX code update, so this doesn't need to be purely YAML or MD files change.
- There are no other changes trough the syllabus in case there is 3rd party involved.

**Comment by Witiko** [comment]
> The current landing page layout is challenging with the space.
> [... W]e can tweak the layout a bit in case of a 3rd party.

Currently, the vertical spaces on the landing page stretch based on the amount of text on the page, i.e. the landing page should be able to fit more text than it might seem. Therefore, we might want to keep the current layout and add the text "Provided by <name of the 3rd party>" together with optional logos below the ISTQB logo similarly to <https://istqb-main-web-prod.s3.amazonaws.com/media/documents/ISTQB-CT-UT_Syllabus_v1.0_2018.pdf>. We can change the layout afterwards if necessary.

> The change could require TeX code update, so this doesn't need to be purely YAML or MD files change.

This change should not require TeX code update. Instead, the file `metadata.yml` would receive a new optional field `provided-by`. Here is an example with four 3rd party organizations without logos:

``` yaml
provided-by:
- name: Alliance for Qualification
- name: Artificial Intelligence United # or just:
- Chinese Software Testing Qualifications Board 
- Korean Software Testing Qualifications Board
```

Here is an example with four 3rd party organizations with logos:

``` yaml
provided-by:
- name: Alliance for Qualification
  logo: logo-a4q  # might refer to the image file `img/logo-a4q.pdf`
- name: Artificial Intelligence United
  logo: logo-aiu
- name: Chinese Software Testing Qualifications Board
  logo: logo-cstqb
- Korean Software Testing Qualifications Board
  logo: logo-kstqb
```
